- repo: https://github.com/pre-commit/mirrors-black
  rev: v22.3.0
  hooks:
    - id: black
      language_version: python3

- repo: https://github.com/pre-commit/mirrors-flake8
  rev: v4.0.1
  hooks:
    - id: flake8
      additional_dependencies: [flake8==4.0.1]
